@hostname = http://localhost:3000

### Get all todo items
GET {{hostname}}/todoitem

### Create a todo item
POST {{hostname}}/todoitem
Content-Type: application/json

{
  "title": "Buy groceries"
}

### Update a todo item
PUT {{hostname}}/todoitem/1
Content-Type: application/json

{
  "title": "Buy groceries and cook dinner",
  "isCompleted": true
}

### Delete a todo item
DELETE {{hostname}}/todoitem/1
